#define CHANNEL_HOP_INTERVAL 5000

#define BUTTON_UP_IO_MUX        PERIPHS_IO_MUX_MTDI_U
#define BUTTON_UP_IO_NUM        12
#define BUTTON_UP_IO_FUNC       FUNC_GPIO12
#define BUTTON_DOWN_IO_MUX      PERIPHS_IO_MUX_MTCK_U
#define BUTTON_DOWN_IO_NUM      13
#define BUTTON_DOWN_IO_FUNC     FUNC_GPIO13
#define BUTTON_LEFT_IO_MUX      PERIPHS_IO_MUX_GPIO0_U 
#define BUTTON_LEFT_IO_NUM      0 
#define BUTTON_LEFT_IO_FUNC     FUNC_GPIO0
#define BUTTON_RIGHT_IO_MUX     PERIPHS_IO_MUX_MTMS_U
#define BUTTON_RIGHT_IO_NUM     14
#define BUTTON_RIGHT_IO_FUNC    FUNC_GPIO14
